name: Package Application with Pyinstaller

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        env:
          PYTHON_VERSION: 3.12.3
        with:
          path: .

      - uses: actions/upload-artifact@v2
        with:
          name: stamper.exe
          path: dist/windows
