name: Package Application with Pyinstaller

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/windows/stamper/stamper.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/windows/stamper/stamper.exe
          token: ${{ secrets.GITHUB_TOKEN }}
