name: Package Application with Pyinstaller

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        env:
          PYTHON_VERSION: 3.12.3
        with:
          path: .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/windows/stamper/stamper.exe
